### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by brettz9**
Hi,

There was a breaking change in one of the dependencies of my CDN-updating tool (despite it even only being a patch upgrade), so I had to make an update, and thought I'd offer an update here. I also updated everything else (except for bootstrap since that didn't have updated CDN versions, at least on the CDN we had been using).

~Note that `npm-check-updates` is a convenient, global npm install I use to check for updates, so the RC file is just to let it know not to auto-update bootstrap in `package.json` the next time someone attempts to update all the dependencies (it needs to be manually checked to see if a CDN is available if you want to use an updated version).~

- Update: `qiblih.js` build per latest devDeps.; update CDNs
~- npm-check-updates: Provide RC file to disable checks for bootstrap updates for now when executing `npm-check-updates`~
~- npm: Hard-code bootstrap version for now (in `package.json`) as CDN not available for later versions~
- npm: Update devDeps.

### CODE REVIEW

**Comment by brettz9** [comment]
Oh, and the Esri-leaflet changes from the latest patch version (see https://github.com/Esri/esri-leaflet-geocoder/compare/v2.3.4...v3.0.0 and https://github.com/Esri/esri-leaflet/compare/v2.5.3...v3.0.0 ), seem to add an API key, but it doesn't seem to be enforced yet (though their release notes said they were still planning to document, so perhaps they may be adding this requirement soon).

**Comment by wtip** [comment]
Thanks Brett! I'll try to review this ASAP

**Comment by brettz9** [comment]
I discovered that bootstrap had indeed deprecated their old CDN, so I stopped making it the default of the CDN-checking `integrity-matters`, so that when updating the CDN URLs/integrity in `qiblih-website` accordingly, bootstrap could be properly updated, and the PR could cease to pin bootstrap from an update.

Note that Bootstrap 5 is in beta now, but I didn't do that update. Whenever we may update the version, its dependency files will apparently need to be changed, so I added a code comment about this as a heads up on where to find that dependency information. If you *never* want to update bootstrap beyond say a patch version (preferring to keep the CSS style as it is), let me know, and I can add a directive to prevent `npm-check-updates` updating this.

So, now I think everything should be in order.

**Comment by wtip** [comment]
It looks like the `esri-leaflet` upgrade broke the search box. If I try entering a city in the deploy preview it doesn't return a result. https://deploy-preview-15--qiblih.netlify.app/

**Comment by brettz9** [comment]
Sure, I can revert that, but do you maybe want to report it to them? (I figure you know better how it is supposed to work.) I don't see any console errors, so I think it is less likely to be an API problem, so it may be good to find out whether this feature is on the way out with them or what.

**Comment by brettz9** [comment]
I guess maybe we should wait until they provide their release notes. I'll see about reverting for now.

**Comment by brettz9** [comment]
I've reverted and the search appears to be working again.

**Review by wtip — APPROVED** [review]
Looks good. Thanks for doing this!

**Pull request merged**
